[package]
name = "cellrs"
version = "0.1.0"
authors = ["leglesslamb <wu.rupert@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battery = "0.7.5"
chrono = "0.4"
termion = "1.5.3"